@startuml borrarPresupuesto
|Administrador|
start 
:Ha ejecutado con éxito el CU Buscar avanzado presupuestos;
repeat
:Seleccionado el presupuesto que desea borrar;
repeat while(El presupuesto se encuentra en estado "Vendido") is (V)
|ZMGestion|
:Borra el presupuesto y muestra un mensaje indicando el éxito de la operación;
|Administrador|
end
@enduml