@startuml buscarAvanzadoProductos
|Vendedor|
start
:Accede a la pantalla para buscar productos;
|ZMGestion|
repeat
:Muestra un formulario para que el vendedor ingrese la cadena de busqueda,
elegir grupo y categoría de producto y si se desea 
buscar prodcutos dados de baja;
|Vendedor|
:Completa los campos solicitados;
|ZMGestion| 
:Busca por nombre de producto, grupo y categoría y estado;
repeat while(No se encontraron coincidencias)
:Lista las coincidencias encontradas;
end
@enduml