@startuml crearProductoFinal
|Vendedor|
start
:Ingresa a la pantalla para crear productos finales;
|ZMGestion|
repeat
:Muestra un formulario para seleccionar el producto,
tipo de producto, tela y lustre;
|Vendedor|
:Selecciona el producto, tipo de producto, tela y lustre;
|ZMGestion|
repeat while(Un producto final ya existe con dicho producto, tipo de producto, tela y lustre.)
:Crea el producto final con los campos ingresados por el vendedor y 
 muestra un mensaje indicando el éxito de la operación;
|Vendedor|
end
@enduml