@startuml enviarPresupuestoEmail
|Vendedor|
:Ha ejecutado con éxito el CU Buscar avanzado presupuestos;
repeat
:Selecciona el presupuesto que desea enviar por correo electrónico;
|ZMGestion|
:Genera en formato PDF el presupuesto;
repeat while(Ël cliente no posee un correo electrónico) is (V)
:Envia el presupuesto por correo electrónico al correo del cliente asociado al presupuesto;
end
@enduml