@startuml iniciarSesion
|Usuario|
start
:Ingresa la dirección de la aplicación en un dispositivo
conectado a Internet;
|ZMGestion|
repeat
repeat
repeat
:Muestra un formulario para que el usuario ingrese su
nombre de usuario y contraseña;
|Usuario|
:El usuario introduce su nombre de usuario y contraseña;
|ZMGestion|
repeat while(El nombre de usuario ingresado existe) is (F)
repeat while(El usuario se encuentra activo) is (F)
repeat while(La contraseña ingresada es incorrecta 
y no supero el limite de intentos permitidos) is (V)
if(La contraseña ingresada es incorrecta 
y supero el limite de intentos permitidos ) then (V)
:Bloquea al usuario;
else (F)
:Genera el token de sesión y lo almacena;
:Trae los permisos del usuario y le muestra sus opciones;
endif
|Usuario|
end
@enduml