@startuml modificarPresupuesto
|Vendedor|
start 
:Ha ejecutado con éxito el CU Buscar avanzado presupuestos;
:Selecciona el presupuesto que desea modificar;
|ZMGestion|
:Lista todas las lineas de presupuesto mostrando las opciones de modificar y borrar;
repeat
repeat
:Mustra un formulario autocmpletado con el cliente y el periodo de validez;
|Vendedor|
:Borra o modifica las lineas que desea cambiar del presupuesto;
if(Tiene permisos de cambio de periodo de validez) then (V)
:Modifica el periodo de validez;
endif
|ZMGestion|
:Modifica el cliente;
repeat while(El cliente y/o el periodo de validez están vacios) is (V)
repeat while(El presupuesto está en estado "Vendido") is (V)
:Modifica el presupuesto y muestra un mensaje indicando el éxito de la operación;
end
@enduml