@startuml Clases
class Personas{
   nombres: string
   apellidos: string
   telefono: string
   email: string
   +idTipoDocumento: int
   documento: string
   estado: string
}

class Usuarios {
   +idUsuario : int
   usuario: string
   password: string
   token: string
   fechaNacimiento: DateTime
   fechaInicio: DateTime
   fechaFin: DateTime
   estadoCivil: string
   cantidadHijos: int
}

class TiposDocumento{
   +idTipoDocumento: int
   tipoDocumento: string
   estado: string
}

class Roles{
    +idRol: int
    rol: string
}

class Permisos{
    +idPermiso: int
    permiso: string
}

class PermisosRol{
    +idRol: int
    +idPermiso: int
}

class Clientes{
    +idCliente: int
    tipo: string
    razonSocial: string 
    +idPais: int
}

class Paises{
    +idPais: int
    pais: string
}

class Provincias{
    +idProvincia: int
    +idPais: int
    provincia: string
}

class Ciudades{
    +idCiudad: int
    +idPais: int
    +idProvincia: int
    ciudad: string
    
}

class Domicilios{
    +idDomicilio: int
    domicilio: string
    codigoPostal: string
    +idCliente: int
    +idCiudad: int
    +idProvincia: int
    +idPais: int
}

class Ubicaciones{
    +idUbicacion: int
    +idDomicilio: int
    ubicacion: string
    estado: string
}

class Productos{
    +idProducto: int
    producto: string
    longitudTela: float
    +idPrecio: int
    +idCategoriaProducto: int
    +idGrupoProducto: int
    +idTipoProducto: int
}

class CategoriasProducto{
    +idCategoriaProducto: int
    categoria: string
}

class GruposProducto{
    +idGrupoProducto: int
    grupo: string
    estado: string
}

class Precios{
    +idPrecio: int
    precio: float
    estado: string
    fechaAlta: DateTime
}

class Telas{
    +idTela: int
    tela: string
    +idPrecio: int
    estado: string
}

class Lustres{
    +idLustre: int
    lustre: string
}

class ProductosFinales{
    +idProductoFinal: int   
    +idProducto: int
    +idLustre: int
    +idTela: int
    estado: string  
}

class TiposProducto{
    +idTipoProducto: int
    tipoProducto: string
}

class Ventas{
    +idVenta: int
    +idCliente: int
    +idDomicilio: int
    +idUbicacion: int
    +idUsuario: int
    fechaAlta: DateTime
    estado: string
}

class LineasProducto{
    +idLineaProducto: int
    +idReferencia: int
    tipo: string
    +idRemito: int
    +idProductoFinal: int
    precioUnitario: float
    cantidad: int
    estado: string
}

class Tareas{
    +idTarea: int
    +idLineaProducto: int
    +idUsuarioFabricante: int
    +idUsuarioRevisor: int
    tarea: string
    fechaAlta: DateTime
    fechaFinalizacion: DateTime
    fechaRevision: DateTime
    estado: string
    observaciones: string
}

class Observaciones{
    +idLineaProducto: int
    +idObservacion: int
    observacion: string
}

class OrdenesProduccion{
    +idOrdenProduccion: int
    +idUsuario: int
    +idVenta: int
    fechaAlta: DateTime
    fechaFinalizacion: DateTime
    estado: string
}

class Presupuestos{
    +idPresupuesto: int
    +idCliente: int
    +idCliente: int
    +idUsuario: int
    fechaAlta: DateTime
    periodoValidez: int
    estado: string
}

class Comprobantes{
    +idComprobante: int
    +idVenta: int
    tipo: string
    numeroComprobante: int
    monto: double
    fechaAlta: DateTime
    estado: string
}


class Remitos{
    +idRemito: int
    +idUbicacion: int
    +idDomicilio: int
    tipo: string
    fechaAlta: DateTime
    fechaEntrega: DateTime
}


@enduml