@startuml diagramaClases

!include ./Clases/Personas.puml
!include ./Clases/Usuarios.puml
!include ./Clases/TiposDocumento.puml
!include ./Clases/Roles.puml
!include ./Clases/Permisos.puml
!include ./Clases/PermisosRol.puml
!include ./Clases/Clientes.puml
!include ./Clases/Paises.puml
!include ./Clases/Provincias.puml
!include ./Clases/Ciudades.puml
!include ./Clases/Domicilios.puml
!include ./Clases/Productos.puml
!include ./Clases/CategoriasProducto.puml
!include ./Clases/GruposProducto.puml
!include ./Clases/TiposProducto.puml
!include ./Clases/Lustres.puml
!include ./Clases/Precios.puml
!include ./Clases/Telas.puml
!include ./Clases/ProductosFinales.puml
!include ./Clases/Presupuestos.puml
!include ./Clases/Ventas.puml
!include ./Clases/Comprobantes.puml
!include ./Clases/Domicilios.puml
!include ./Clases/OrdenesProduccion.puml
!include ./Clases/LineasProducto.puml
!include ./Clases/Observaciones.puml
!include ./Clases/Remitos.puml
!include ./Clases/Ubicaciones.puml
!include ./Clases/Tareas.puml
!include ./Clases/LineasPresupuesto.puml
!include ./Clases/LineasVenta.puml
!include ./Clases/LineasOrdenProduccion.puml
!include ./Clases/LineasRemito.puml

  

left to right direction
Personas <|-- Usuarios
Personas <|-- Clientes
LineasProducto <|-- LineasPresupuesto
LineasProducto <|-- LineasVenta
LineasProducto <|-- LineasOrdenProduccion
LineasProducto <|-- LineasRemito
LineasProducto "1" -- "0..1" LineasProducto
TiposDocumento "1"--"0..*" Personas
Paises  *-- "1..*" Provincias
Provincias  *-- "1..*" Ciudades
Paises "1"--"0..*" Clientes
Domicilios "0..*"--"1" Domicilios
Domicilios "0..*"--"0..1" Clientes
Roles "1"  -- "1..*" PermisosRol
Permisos "1"  -- "1..*" PermisosRol
Usuarios "0..*" -- "1" Roles
Ubicaciones "0..1"--"1" Domicilios
Productos "0..*" -- "1" GruposProducto
Productos "0..*" -- "1" CategoriasProducto
Productos  "1"-- "1..*" Precios
Telas  "1"-- "1..*" Precios
OrdenesProduccion "0..*" -- "1" Usuarios
ProductosFinales "0..*"--"1" Productos
ProductosFinales "0..*"--"0..1" Telas
ProductosFinales "0..*"--"0..1" Lustres
Productos "0..*"--"1" TiposProducto
Ventas "0..*" -- "1" Usuarios
Ventas "0..*" -- "1" Clientes
Ventas "0..*" -- "0..1" Domicilios
Ventas "0..*" -- "1" Ubicaciones
Ventas "0..1" -- "0..*" Presupuestos
Ventas "0..1" -- "0..1" OrdenesProduccion
Ventas "1" -- "0..*" Comprobantes
LineasVenta "0..*"--* Ventas
LineasOrdenProduccion "0..*"--* OrdenesProduccion
LineasPresupuesto "0..*"--* Presupuestos
Observaciones "0..*"--* LineasOrdenProduccion
LineasRemito "0..*"--* Remitos
LineasRemito "0..*" -- "1" Ubicaciones
LineasProducto "0..*"--"1" ProductosFinales
Presupuestos "0..*"--"1" Clientes
Presupuestos "0..*"--"1" Usuarios
Remitos "0..*"--"0..1" Domicilios
Ubicaciones "1"--"0..*" Remitos
Tareas "0..*"--"1" Usuarios
Tareas "0..*"--"0..1" Usuarios
Tareas "0..*"--* LineasOrdenProduccion
Tareas "1"--"0..1" Tareas
@enduml

@enduml

@startuml vistaProductos
!include ./Clases/Productos.puml
!include ./Clases/CategoriasProducto.puml
!include ./Clases/GruposProducto.puml
!include ./Clases/Telas.puml
!include ./Clases/Lustres.puml
!include ./Clases/Precios.puml
!include ./Clases/ProductosFinales.puml
!include ./Clases/TiposProducto.puml

left to right direction
Productos "0..*" -- "1" CategoriasProducto
Productos "0..*" -- "1" GruposProducto
Productos "1"-- "1..*" Precios
Productos "0..*" -- "1" TiposProducto
Telas "1"-- "1..*" Precios
ProductosFinales "0..*"--"1" Productos
ProductosFinales "0..*"--"0..1" Telas
ProductosFinales "0..*"--"0..1" Lustres
@enduml

@startuml vistaSistema
!include ./Clases/Personas.puml
!include ./Clases/Usuarios.puml
!include ./Clases/TiposDocumento.puml
!include ./Clases/Permisos.puml
!include ./Clases/Roles.puml
!include ./Clases/PermisosRol.puml

left to right direction
Personas <|-- Usuarios
TiposDocumento "1"--"0..*" Personas
Roles "1"  -- "1..*" PermisosRol
Permisos "1"  -- "1..*" PermisosRol
Usuarios "0..*" -- "1" Roles

@enduml

@startuml vistaPresupuestosVentas
!include ./Clases/ProductosFinales.puml
!include ./Clases/LineasProducto.puml
!include ./Clases/LineasVenta.puml
!include ./Clases/LineasPresupuesto.puml
!include ./Clases/Ventas.puml
!include ./Clases/Presupuestos.puml
!include ./Clases/Comprobantes.puml

left to right direction
LineasProducto <|-- LineasVenta
LineasProducto <|-- LineasPresupuesto
LineasProducto "1" -- "0..1" LineasProducto
LineasVenta "0..*"--* Ventas
LineasPresupuesto "0..*"--* Presupuestos
Ventas "0..*" -- "1" Clientes
Presupuestos "0..*"--"1" Clientes
Ventas "0..1" -- "0..*" Presupuestos
LineasProducto "0..*"--"1" ProductosFinales
Ventas "1" -- "0..*" Comprobantes
@enduml

@startuml vistaClientes
!include ./Clases/Personas.puml
!include ./Clases/Clientes.puml
!include ./Clases/TiposDocumento.puml
!include ./Clases/Paises.puml
!include ./Clases/Provincias.puml
!include ./Clases/Ciudades.puml
!include ./Clases/Domicilios.puml

left to right direction
Personas <|-- Clientes
Paises  *-- "1..*" Provincias
Provincias  *-- "1..*" Ciudades
Paises "1"--"0..*" Clientes
Domicilios "0..*"--"0..1" Clientes
TiposDocumento "1"--"0..*" Personas
Domicilios "0..*" -- "1" Ciudades
@enduml

@startuml vistaProduccion
!include ./Clases/Usuarios.puml
!include ./Clases/Tareas.puml
!include ./Clases/OrdenesProduccion.puml
!include ./Clases/ProductosFinales.puml
!include ./Clases/Observaciones.puml
!include ./Clases/LineasProducto.puml
!include ./Clases/LineasOrdenProduccion.puml


left to right direction
LineasProducto "1" -- "0..1" LineasProducto
LineasProducto <|-- LineasOrdenProduccion
LineasOrdenProduccion "0..*"--* OrdenesProduccion
Tareas "0..*"--"1" Usuarios
Tareas "0..*"--"0..1" Usuarios
Tareas "0..*"--* LineasOrdenProduccion
Tareas "1"--"0..1" Tareas
Observaciones "0..*"--* LineasOrdenProduccion
LineasProducto "0..*"--"1" ProductosFinales
OrdenesProduccion "0..*" -- "1" Usuarios
@enduml

@startuml vistaEntregas
!include ./Clases/Ubicaciones.puml
!include ./Clases/Domicilios.puml
!include ./Clases/LineasProducto.puml
!include ./Clases/LineasRemito.puml
!include ./Clases/Remitos.puml

LineasProducto "1" -- "0..1" LineasProducto
LineasProducto <|-- LineasRemito
LineasRemito "0..*"--* Remitos
LineasRemito "0..*" -- "1" Ubicaciones
Ubicaciones "0..1"--"1" Domicilios
Remitos "0..*"--"0..1" Domicilios 
Ubicaciones "1"--"0..*" Remitos
@enduml

@startuml fichaTecnicaClases
!include ./Clases/Personas.puml
!include ./Clases/Usuarios.puml
!include ./Clases/TiposDocumento.puml
!include ./Clases/Roles.puml
!include ./Clases/Permisos.puml
!include ./Clases/PermisosRol.puml
!include ./Clases/Clientes.puml
!include ./Clases/Paises.puml
!include ./Clases/Provincias.puml
!include ./Clases/Ciudades.puml
!include ./Clases/Domicilios.puml
!include ./Clases/Productos.puml
!include ./Clases/CategoriasProducto.puml
!include ./Clases/GruposProducto.puml
!include ./Clases/TiposProducto.puml
!include ./Clases/Lustres.puml
!include ./Clases/Precios.puml
!include ./Clases/Telas.puml
!include ./Clases/ProductosFinales.puml
!include ./Clases/Presupuestos.puml
!include ./Clases/Ventas.puml
!include ./Clases/Comprobantes.puml
!include ./Clases/Domicilios.puml
!include ./Clases/OrdenesProduccion.puml
!include ./Clases/LineasProducto.puml
!include ./Clases/LineasRemito.puml
!include ./Clases/LineasPresupuesto.puml
!include ./Clases/LineasVenta.puml
!include ./Clases/LineasOrdenProduccion.puml
!include ./Clases/Observaciones.puml
!include ./Clases/Remitos.puml
!include ./Clases/Ubicaciones.puml
!include ./Clases/Tareas.puml
!include ./Gestores/GestorClientes.puml 
!include ./Gestores/GestorGruposProducto.puml
!include ./Gestores/GestorOrdenesProduccion.puml
!include ./Gestores/GestorPresupuestos.puml
!include ./Gestores/GestorProductos.puml
!include ./Gestores/GestorProductosFinales.puml
!include ./Gestores/GestorRemitos.puml
!include ./Gestores/GestorRoles.puml
!include ./Gestores/GestorTelas.puml
!include ./Gestores/GestorUbicaciones.puml
!include ./Gestores/GestorUsuarios.puml
!include ./Gestores/GestorVentas.puml
!include ./Gestores/GestorComprobantes.puml
!include ./Enumeraciones/Status.puml
!include ./Clases/Response.puml

@enduml

@startuml vistaCanonica
top to bottom direction
!include ./Gestores/Implementaciones.puml
!include ./Clases/Usos.puml

@enduml