@startuml Clientes
class Clientes{
    +idCliente: int
    tipo: string
    razonSocial: string 
    +idPais: int

    listarDomicilios(): List<Domicilios>
    listarVentas(): List<Ventas>
    listarPresupuestos(): List<Presupuestos>
    crearDomicilio(domicilio Domicilios): string
    borrarDomicilio(domicilio Domicilios): string    
}
@enduml