@startuml Clientes
hide circle
class Clientes{
    idCliente: int
    tipo: string
    razonSocial: string 
    idPais: int

    listarDomicilios(): List<Domicilios>
    listarVentas(): List<Ventas>
    listarPresupuestos(): List<Presupuestos>
    crearDomicilio(domicilio Domicilios): Reponse
    borrarDomicilio(domicilio Domicilios): Response    
}
@enduml