@startuml Comprobantes
hide circle
class Comprobantes{
    idComprobante: int
    idVenta: int
    idUsuario: int
    tipo: string
    numeroComprobante: int
    monto: double
    fechaAlta: DateTime
    fechaBaja: DateTime
    estado: string
    observaciones: string
}
@enduml