@startuml GruposProducto
class GruposProducto{
    +idGrupoProducto: int
    grupo: string
    fechaAlta: DateTime
    fechaBaja: DateTime
    descripcion: string
    estado: string

    listarProductos(): List<Productos>
    modificarPreciosProductos(porcentaje float): Response
}
@enduml