@startuml LineasOrdenProduccion
hide circle
class LineasOrdenProduccion{
    idOrdenProduccion: int

    reanudar(): Response
    listarObservaciones(): List<Observaciones>
    listarTareas(): List<Tareas>
    crearObservacion(observacion Observaciones): Response
    borrarObservacion(observacion Observaciones): Response
    crearTarea(tarea Tareas): Response
    borrarTarea(tarea Tareas): Response
    todasTareasPendientes(): bool
    tieneTareas(): bool

}
@enduml