@startuml LineasOrdenProduccion
class LineasOrdenProduccion{
    +idOrdenProduccion: int

    listarObservaciones(): List<Observaciones>
    listarTareas(): List<Tareas>
    verificar(): string
    cancelar(): string
    reanudar(): string
    crearObservacion(observacion Observaciones): string
    borrarObservacion(observacion Observaciones): string
}
@enduml