@startuml LineasProducto
class LineasProducto{
    +idLineaProducto: int
    +idLineaProductoPadre: int
    +idRemito: int
    +idProductoFinal: int
    precioUnitario: float
    cantidad: int
    estado: string

    dameRemito():Remitos
    listarObservaciones(): List<Observaciones>
    listarTareas(): List<Tareas>
    crearObservacion(observacion Observaciones): string
    borrarObservacion(observacion Observaciones): string
    crearTarea(tarea Tareas): string
    borrarTarea(tarea Tareas): string
    todasTareasPendientes(): bool
    tieneTareas(): bool
    verificar(): string
}
@enduml