@startuml LineasProducto
class LineasProducto{
    +idLineaProducto: int
    +idLineaProductoPadre: int
    +idRemito: int
    +idProductoFinal: int
    precioUnitario: float
    cantidad: int
    estado: string

    dameRemito():Remitos
    cancelar():Response
    damePadre(): IObjeto
    precioTotal(): float
}
@enduml