@startuml OrdenesProduccion
class OrdenesProduccion{
    +idOrdenProduccion: int
    +idUsuario: int
    +idVenta: int
    fechaAlta: DateTime
    fechaFinalizacion: DateTime
    estado: string

    cancelar(): string
    crearLineaOrdenProduccion(lineaOrdenProduccion LineasOrdenProduccion): string
    modificarLineaOrdenProduccion(lineaOrdenProduccion LineasOrdenProduccion): string
    borrarLineaOrdenProduccion(lineaOrdenProduccion LineasOrdenProduccion): string
    listarLineasOrdenProduccion(): List<LineasOrdenProduccion>
    pasarAPendiente():string
}
@enduml