@startuml Personas
hide circle
class Personas{
   nombres: string
   apellidos: string
   telefono: string
   email: string
   idTipoDocumento: int
   documento: string
   estado: string
   fechaAlta: DateTime
   fechaBaja: DateTime
   
   listarPresupuestos(): List<Presupuestos>
   listarVentas(): List<Ventas>
}
@enduml