@startuml Presupuestos
class Presupuestos{
    +idPresupuesto: int
    +idUbicacion: int
    +idCliente: int
    +idUsuario: int
    fechaAlta: DateTime
    periodoValidez: int
    estado: string

    crearLineaPresupuesto(lineaPresupuesto LineasPresupuesto): Response
    modificarLineaPresupuesto(lineaPresupuesto LineasPresupuesto): Response
    borrarLineaPresupuesto(lineaPresupuesto LineasPresupuesto): Response
    listarLineasPresupuesto(): List<LineasPresupuesto>
    enviarPresupuestoEmail(f File): Response
    generarPDF(): File
    pasarACreado(): Response
    estaExpirado(): bool
}
@endumls