@startuml Presupuestos
class Presupuestos{
    +idPresupuesto: int
    +idUbicacion: int
    +idCliente: int
    +idUsuario: int
    fechaAlta: DateTime
    periodoValidez: int
    estado: string

    crearLineaPresupuesto(lineaPresupuesto LineasPresupuesto): string
    modificarLineaPresupuesto(lineaPresupuesto LineasPresupuesto): string
    borrarLineaPresupuesto(lineaPresupuesto LineasPresupuesto): string
    listarLineasPresupuesto(): List<LineasPresupuesto>
    enviarPresupuestoEmail(): string
    generarPDF(): File
    pasarACreado(): string
    estaExpirado(): bool
}
@endumls