@startuml ProductosFinales
class ProductosFinales{
    +idProductoFinal: int   
    +idProducto: int
    +idLustre: int
    +idTela: int
    estado: string

    dameStock():int
    dameStockPorUbicacion(u Ubicaciones): int

    
}
@enduml