@startuml Productos
class Productos{
    +idProducto: int
    producto: string
    longitudTela: float
    +idPrecio: int
    +idCategoriaProducto: int
    +idGrupoProducto: int
    +idTipoProducto: int
    fechaAlta: DateTime
    fechaBaja: DateTime
    observaciones: string

    listarPrecios(): List<Precios>
    damePrecioActual(): Precios
    dameTipoProducto(): TiposProducto
    dameCategoriaProducto(): Categorias
}
@enduml