@startuml ProductosFinales
hide circle
class ProductosFinales{
    idProductoFinal: int   
    idProducto: int
    idLustre: int
    idTela: int
    fechaAlta: DateTime
    fechaBaja: DateTime
    estado: string

    dameStock():int
    dameStockPorUbicacion(u Ubicaciones): int

    
}
@enduml