@startuml ProductosFinales
class ProductosFinales{
    +idProductoFinal: int   
    +idProducto: int
    +idLustre: int
    +idTela: int
    estado: string

    listarLustres(): List<Lustres>
}
@enduml