@startuml Remitos
class Remitos{
    +idRemito: int
    +idUbicacion: int
    +idDomicilio: int
    tipo: string
    fechaAlta: DateTime
    fechaEntrega: DateTime
    cancelar(): string
    descancelar(): string
    entregar(): string

    crearLineaRemito(lineaRemito LineasRemito): string
    modificarLineaRemito(lineaRemito LineasRemito): string
    borrarLineaRemito(lineaRemito LineasRemito): string
    listarLineasRemito(): List<LineasRemito>
}
@enduml