@startuml Remitos
class Remitos{
    +idRemito: int
    +idUbicacion: int
    +idDomicilio: int
    tipo: string
    fechaAlta: DateTime
    fechaEntrega: DateTime
    
    cancelar(): Response
    descancelar(): Response
    entregar(): Response
    asociarVentar(v Venta): Response
    asignarLineas(lv List<LineasVenta>):Response
    crearLineaRemito(lineaRemito LineasRemito): Response
    modificarLineaRemito(lineaRemito LineasRemito): Response
    borrarLineaRemito(lineaRemito LineasRemito): Response
    listarLineasRemito(): List<LineasRemito>
    pasarACreado(): Response
    estaCancelado(): bool
    asociadoAVenta(): bool
    dividir(lv List<LineasVenta>): Response
}
@enduml