@startuml Tareas
class Tareas{
    +idTarea: int
    +idLineaProducto: int
    +idUsuarioFabricante: int
    +idUsuarioRevisor: int
    tarea: string
    fechaAlta: DateTime
    fechaFinalizacion: DateTime
    fechaRevision: DateTime
    estado: string
    observaciones: string

    ejecutar(): string
    cancelar(): string
    reanudar(): string
    pausar(): string
    finalizar(): string
    verificar(): string
    
}
@enduml