@startuml Tareas
class Tareas{
    +idTarea: int
    +idLineaProducto: int
    +idUsuarioFabricante: int
    +idUsuarioRevisor: int
    tarea: string
    fechaAlta: DateTime
    fechaFinalizacion: DateTime
    fechaRevision: DateTime
    estado: string
    observaciones: string

    ejecutar(): Response
    cancelar(): Response
    reanudar(): Response
    pausar(): Response
    finalizar(): Response
    verificar(): Response
    
}
@enduml