@startuml Ubicaciones
hide circle
class Ubicaciones{
    idUbicacion: int
    idDomicilio: int
    ubicacion: string
    fechaAlta: DateTime
    fechaBaja: DateTime
    observaciones: string
    estado: string

    listarPresupuestos(): List<Presupuestos>
    listarVentas(): List<Ventas>
    listarRemitos(): List<Remitos>
    listarUsuarios(): List<Usuarios>
    generarStock(): Map<Productos, int>
    dameDomicilio(): Domicilios
}
@enduml