@startuml Usuarios
class Usuarios {
   +idUsuario : int
   +idUbicacion: int
   usuario: string
   password: string
   token: string
   fechaNacimiento: DateTime
   fechaInicio: DateTime
   estadoCivil: string
   cantidadHijos: int

   iniciarSesion(): Response
   cerrarSesion(): Response
   listarOrdenesProduccion(): List<OrdenesProduccion>
   listarTareas(): List<Tareas>
}
@enduml