@startuml Ventas
class Ventas{
    +idVenta: int
    +idCliente: int
    +idDomicilio: int
    +idUbicacion: int
    +idUsuario: int
    fechaAlta: DateTime
    estado: string

    generarOrdenProduccion(lv List<LineasVenta>): Response
    generarRemito(lv List<LineasVenta>): Response
    revisar(): Response
    crearComprobante(comprobante Comprobantes): Response
    crearLineaVenta(lineaVenta LineasVenta): Response
    modificarLineaVenta(lineaVenta LineasVenta): Response
    borrarLineaVenta(lineaVenta LineasVenta): Response
    listarLineasVenta(): List<LineasVenta>
    desvincularRemito(lv LineasVenta)
    puedeProducir(lv List<LineasVenta>): bool
    totalPagado(): float
    totalRetirado(): float
    obtenerSaldo(): float
    chequearPrecios(): Response
    todasLineasCanceladas(): bool
    todasLineasNoCanceladasEntregadas(): bool
    reservar(lv List<LineasVenta>): Response

}
@enduml