@startuml empleados
Alta: Estado = "A"
Baja: Estado = "B"

top to bottom direction
[*] --> Alta: GestorEmpleados.\ncrear\n(empleado Empleados)
Alta --> [*]: GestorEmpleados.\nborrar\n(empleado Empleados)
Baja --> [*]: GestorEmpleados.\nborrar\n(empleado Empleados)
Alta --> Baja: Empleados.\ndarBaja()
Baja --> Alta: Empleados.\ndarAlta()

@enduml

@startuml tareas
Pendiente: Estado = "P"
EnProceso: Estado = "E"
Finalizada: Estado = "F"
Pausada: Estado = "S"
Cancelada: Estado = "C"
Verificada: Estado = "V"


[*] --> Pendiente: LineasProducto.\ncrearTarea\n(tarea Tareas)
Pendiente --> [*]: LineasProducto.\nborrarTarea\n(tarea Tareas)
Cancelada --> [*]: LineasProducto.\nborrarTarea\n(tarea Tareas)
Pendiente --> EnProceso: Tareas.\nejecutar()
EnProceso --> Cancelada: Tareas.\ncancelar()
EnProceso --> Finalizada: Tareas.\nfinalizar()
EnProceso --> Pausada: Tareas.\npausar()
Finalizada --> EnProceso: Tareas.\nreanudar()
Pausada --> EnProceso: Tareas.\nreanudar()
Pausada --> Cancelada: Tareas.\ncancelar()
Cancelada --> EnProceso: Tareas.\nreanudar()
Finalizada --> Cancelada: Tareas.\ncancelar()
Finalizada --> Verificada: Tareas.\nverificar()
Verificada --> EnProceso: Tareas.\nreanudar()

@enduml

@startuml lineasProducto
Pendiente: Estado = "P" AND
Pendiente: this.estaPendiente()
Produciendo: Estado = "P" AND
Produciendo: this.estaEnProduccion()
Cancelada: Estado = "C"
NoUtilizada: Estado = "N"
Utilizada: Estado = "U"
PendienteDeProduccion: Estado = "F " AND
PendienteDeProduccion:(NOT this.\ntieneTareas() OR\n this.\ntodasTareasPendientes())
EnProduccion: Estado = "F" AND
EnProduccion: NOT this.\ntodasTareasPendientes()
Verificada: Estado = "V"
Reservada: Estado = "P" AND
Reservada: LineasVenta.estaReservada()
PendienteDeEntrega: Estado = "P" AND
PendienteDeEntrega: LineasProducto.estaPendienteDeEntrega()
'Hicimos que estado = D para simplicidad en la busqueda.
Entregada: Estado = "P" AND
Entregada: this.estaEntregada() 

top to bottom direction
[*] --> Pendiente: Presupuestos.\ncrearLineaPresupuesto\n(lp LineaPresupuesto)
[*] --> Pendiente: Ventas.\ncrearLineaVenta\n(lv LineasVenta)
[*] --> PendienteDeEntrega: Remitos.\ncrearLineaRemito\n(lr LineasRemito)
Pendiente --> [*]: Ventas.\nborrarLineaVenta\n(lv LineasVenta)
Pendiente --> [*]: Presupuestos.\nborrarLineaPresupuesto\n(lp LineaPresupuesto)
[*] --> PendienteDeProduccion: OrdenesProduccion.\ncrearLineaOrdenProduccion\n(lOP LineasOrdenProduccion)
PendienteDeProduccion --> [*]: OrdenesProduccion.\nborrarLineaOrdenProduccion\n(lOP LineasOrdenProduccion)
Pendiente --> Utilizada: GestorPresupuestos.\ntransformarPresupuestosEnVenta\n(lp List<LineasPresupuesto>)
Utilizada --> Pendiente: GestorVentas.\nborrar\n(venta Ventas)
Pendiente --> NoUtilizada: GestorPresupuestos.\ntransformarPresupuestosEnVenta\n(lp List<LineasPresupuesto>)
NoUtilizada --> Pendiente: GestorVentas.\nborrar\n(venta Ventas)
Utilizada --> NoUtilizada: Ventas.\nborrarLineaVenta\n(lv LineasVenta)
Pendiente --> Cancelada: LineasVenta.\ncancelar()
Pendiente --> PendienteDeProduccion: Ventas.\ngenerarOrdenProduccion\n(lv List<LineasVenta>)
Pendiente --> Produciendo: Ventas.\ngenerarOrdenProduccion\n(lv List<LineasVenta>)
Pendiente --> Reservada: Ventas.\ngenerarRemito\n(lv List<LineasVenta>)
Produciendo --> Pendiente: LineasOrdenProduccion.\ncancelar()
Produciendo --> Reservada: LineasOrdenProduccion.\nverificar()
Reservada --> Pendiente: Remitos.\ncancelar()
PendienteDeProduccion --> Cancelada: LineasOrdenProduccion.\ncancelar()
PendienteDeProduccion --> EnProduccion: Tarea.\nejecutar()
PendienteDeProduccion --> Pendiente: LineasVenta.\ncancelar()
EnProduccion --> Cancelada: LineasOrdenProduccion.\ncancelar()
EnProduccion --> Pendiente: LineasVenta.\ncancelar()
Cancelada --> EnProduccion: LineasOrdenProduccion.\nreanudar()
Cancelada --> PendienteDeProduccion: LineasOrdenProduccion.\nreanudar()
Reservada --> Cancelada: LineasVenta.\ncancelar()
EnProduccion --> Verificada: LineasOrdenProduccion.\nverificar()
Reservada --> PendienteDeEntrega: Ventas.\ncrearComprobante()
PendienteDeEntrega --> Entregada: Remitos.\nentregar()
PendienteDeEntrega --> Cancelada: LineasVenta.\ncancelar()
PendienteDeEntrega --> [*]: Remitos.\nborrarLineaRemito\n(lr LineasRemito)
Entregada --> Cancelada: LineasProducto.\ncancelar()

@enduml

@startuml presupuestos

EnCreacion: Estado = "E"
Creado: Estado = "C"
Vendido: Estado = "V"
Expirado: Estado = "C" AND
Expirado: this.estaExpirado()

[*] --> EnCreacion: GestorPresupuestos.\ncrear\n(p Presupuestos)
EnCreacion --> Creado: this.\npasarACreado()
Creado --> Vendido: GestorPresupuestos.\ntransformarPresupuestosEnVenta\n(lp List<LineasPresupuesto>)
Creado --> Expirado
Vendido --> Creado: GestorVentas.\nborrar\n(venta Ventas)
EnCreacion --> [*]: GestorPresupuestos.\nborrar\n(p Presupuestos)
Creado --> [*]: GestorPresupuestos.\nborrar\n(p Presupuestos)

@enduml

@startuml ventas
top to bottom direction

EnCreacion: Estado = "E"
EnRevision: Estado = "R"
Cancelada: (Estado = "C" OR\n Estado = "R") AND
Cancelada: this.todasLineasCanceladas()
Pendiente: Estado = "C"
Entregada: Estado = "C" AND
Entregada: this.todasLineasNoCanceladasEntregadas()

[*] --> EnCreacion: GestorVentas.\ncrear\n(venta Ventas)
[*] --> EnCreacion: GestorPresupuestos.\ntransformarPresupuestosEnVenta\n(lp List<LineasPresupuesto>)
EnCreacion --> [*]: GestorPresupuestos.\nborrar\n(p Presupuestos)
EnCreacion -> EnRevision: this.\nchequearPrecios()
EnCreacion --> Pendiente: this.\nchequearPrecios()
EnRevision --> Cancelada: LineasProducto.\ncancelar()
EnRevision --> Pendiente: this.\nrevisar()
Pendiente --> Cancelada: LineasProducto.\ncancelar()
Pendiente --> Entregada: LineasRemito.\nentregar()

@enduml

@startuml ordenesProduccion
EnCreacion: Estado = "E"
Pendiente: Estado = "C" AND
Pendiente: OrdenesProduccion.estaPendiente()
EnProduccion: Estado = "C" AND
EnProduccion: OrdenesProduccion.estaEnProduccion()
Verificada: Estado = "C" AND
Verificada: OrdenesProduccion.estaVerificada()
Cancelada: Estado = "C" AND
Cancelada: OrdenesProduccion.estaCancelada()

[*]--> EnCreacion: Ventas.\ngenerarOrdenProduccion\n(lv List<LineasVenta>)
[*]--> EnCreacion: GestorOrdenesProduccion.\ncrear\n(op OrdenesProduccion)
EnCreacion --> [*]: GestorOrdenesProduccion.\nborrar\n(op OrdenesProduccion)
EnCreacion -->Pendiente: this.\npasarAPendiente()
EnProduccion -->Pendiente: LineasOrdenProduccion.\ncancelar()
EnProduccion -->Pendiente: LineasOrdenProduccion.\nverificar()
EnProduccion -->Pendiente: Remitos.\nentregar()
EnProduccion -->Cancelada: LineasOrdenProduccion.\ncancelar()
Pendiente --> EnProduccion: Tareas.\nejecutar()
Pendiente --> EnProduccion: LineasOrdenProduccion.\nreanudar()
Cancelada --> Pendiente: LineasOrdenProduccion.\nreanudar()
Cancelada --> EnProduccion: LineasOrdenProduccion.\nreanudar()
Pendiente --> Cancelada: LineasOrdenProduccion.\ncancelar()
Pendiente --> Verificada: LineasOrdenProduccion.\ncancelar()
EnProduccion --> Verificada: LineasOrdenProduccion.\nverificar()
EnProduccion --> Verificada: LineasOrdenProduccion.\ncancelar()
EnProduccion --> Verificada: GestionRemitos.\ncrear\n(r Remitos)
Verificada --> EnProduccion: LineasOrdenProduccion.\nreanudar()

@enduml

@startuml remitos
top to bottom direction

EnCreacion: Estado = "E"
Creado: Estado = "C"
Creado: FechaEntrega == null
Entregado: Estado = "C"
Entregado: FechaEntrega != null
Cancelado: Estado = "B"

[*] --> EnCreacion: GestorRemitos.\ncrear\n(remito Remitos)
[*] --> EnCreacion: Ventas.\ngenerarRemito\n(lv List<LineasVenta>)
EnCreacion --> Creado: this.\npasarACreado()
Creado --> Entregado: Remitos.\nentregar()
Cancelado --> Creado: Remitos.\ndescancelar()
Creado --> Cancelado: Remitos.\ncancelar()
EnCreacion --> [*]: GestorRemitos.\nborrar\n(remito Remitos)
Creado --> [*]: GestorRemitos.\nborrar\n(remito Remitos)
@enduml