@startuml borrarProducto
|Administrador|
start
:Ha ejecutado con exito el CU Buscar productos avanzado;
repeat
:Indica el producto que quiere borrar;
repeat while(El producto fue utilizado para crear un producto final) is (V)
|ZMGestion|
:Borra el producto y muestra un mensaje indicando el éxito de la 
operación;
|Administrador|
end
@enduml