@startuml crearProducto
|Administrador|
start
:Ingresa a la pantalla para crear productos;
|ZMGestion|
repeat
repeat
repeat
:Muestra un formulario para ingresar el nombre del 
producto, el precio, la cantidad de tela necesaria para
producirlo en caso de ser necesario y dos listas desplegables
para seleccionar la categoría y el grupo al cual pertenece
el producto;
|Administrador|
:Completa el formulario y selecciona de las listas desplegables
el grupo y categoría a la cual pertenece el producto;
|ZMGestion|
repeat while(El nombre ingresado ya existe para el grupo y categoria) is (V)
repeat while(El precio ingresado sea menor o igual a cero) is (V)
repeat while(La cantidad de tela necesaria ingresada sea menor a cero) is (V)
:Crea el producto con los campos ingresados por el usuario y 
 muestra un mensaje indicando el éxito de la operación;
|Administrador|
end
@enduml