@startuml crearPresupuesto
|Vendedor|
start
:Accede a la pantalla para crear presupuestos;
|ZMGestion|
repeat
:Muestra un formulario para que el vendedor seleccione un cliente;
|Vendedor|
:Selecciona un cliente;
|ZMGestion|
repeat while(Ha seleccionado un cliente) is (F)
:Crea un presupuesto en estado de "En creación";
repeat
while(Desea agregar una nueva linea de presupuesto) is (V)
|Vendedor|
:Ejecuta el CU059 Crear linea de presupuesto|
end while
|ZMGestion|
repeat while(Ha ingresado al menos una linea de presupuesto) is (F)
:Cambia el estado del presupuesto a "Creado";
|Vendedor|
end
@enduml