@startuml crearVenta
|Vendendor|
start
:Accede a la pantalla para crear ventas;
|ZMGestion|
:Muestra un formulario para que el vendendor seleccione un cliente;
|Vendendor|
:Selecciona un cliente;
|ZMGestion|
while(Desea agregar una nueva linea de venta) is (V)
:CU Crear linea venta|
end while
:Crea la venta y muestra la opción de modificarla;
|Vendendor|
end
@enduml