@startuml crearCliente
|Vendedor|
start
:Accede a la pantalla para crear clientes;
|ZMGestion|
repeat
repeat
repeat
:Muestra un formulario para que el vendedor ingrese el tipo de persona (física o jurídica),
nombre y apellido (o razón social), tipo y número de docuemento, correo electrónico, número de
telefono y nacionalidad;
|Vendedor|
:Completa el formulario;
|ZMGestion|
repeat while(El vendedor ha dejado un campo obligatorio vacio) is (V)
repeat while(El correo electrónico ingresado ya esta en uso) is (V)
repeat while(El tipo y número de documento ingresado ya existe) is (V)
:Crea el cliente y muestra un mensaje indicando el éxito de la operación;
|Vendedor|
end
@enduml