@startuml borrarPresupuesto
|Administrador|
start 
:Ha ejecutado con éxito el CU057(Buscar avanzado presupuestos);
repeat
:Seleccionado el presupuesto que desea borrar;
repeat while(El presupuesto se encuentra en estado "Vendido") is (V)
|ZMGestion|
:Borra el presupuesto y muestra un mensaje indicando el éxito de la operación;
|Administrador|
end
@enduml

@startuml borrarProducto
|Administrador|
start
:Ha ejecutado con exito el CU(Buscar productos avanzado);
repeat
:Indica el producto que quiere borrar;
repeat while(El producto fue utilizado para crear un producto final) is (V)
|ZMGestion|
:Borra el producto y muestra un mensaje indicando el éxito de la 
operación;
|Administrador|
end
@enduml

@startuml borrarTela
|Administrador|
:Ha ejecutado con éxito el CU(Listar telas);
repeat
:Indica la tela que desea borrar;
repeat while(La tela fue utilizada para crear al menos un producto final) is (V)
|ZMGestion|
:Borra la tela y muestra un mensaje indicando el éxito de la operación;
|Administrador|
end
@enduml

@startuml buscarAvanzadoClientes
|Vendedor|
:Accede a la pantalla para buscar clientes;
|ZMGestion|
repeat
:Muestra un formulario para que el vendedor ingrese la cadena de busqueda,
seleccione el tipo de persona y decida si desea buscar clientes dados de baja;
|Vendedor|
:Completa el formulario;
|ZMGestion|
repeat while(No se econtro ningun resultado para la busqueda) is (V)
:Lista las coincidencias encontradas;
|Vendedor|
end
@enduml

@startuml buscarAvanzadoPresupuestos
|Vendedor|
start
:Accede a la pantalla para buscar presupuestos;
|ZMGestion|
repeat
:Muestra un formulario para que el vendedor seleccione un cliente, producto, tela,
lustre y estado del presupuesto. Siendo todos los campos opcionales;
|Vendedor|
:Completa los campos seleccionados;
|ZMGestion|
:Busca por cliente, producto, tela, lustre y estado del presupuesto;
repeat while(No se encontraron coincidencias) is (V)
:Lista las coincidencias encontradas;
|Vendedor|
end
@enduml

@startuml buscarAvanzadoProductos
|Vendedor|
start
:Accede a la pantalla para buscar productos;
|ZMGestion|
repeat
:Muestra un formulario para que el vendedor ingrese la cadena de busqueda,
elija grupo, categoría y tipo de producto y si se desea 
buscar productos dados de baja;
|Vendedor|
:Completa los campos solicitados;
|ZMGestion| 
:Busca por nombre de producto, grupo, categoría y tipo de producto y estado;
repeat while(No se encontraron coincidencias) is (V)
:Lista las coincidencias encontradas;
|Vendedor|
end
@enduml



@startuml buscarAvanzadoOrdenesProduccion
|Fabricantes|
start
:Accede a la pantalla para buscar órdenes de producción;
|ZMGestion|
repeat
:Muestra un formulario para que el fabricante ingrese un producto, tela,
lustre y estado de la orden de producción. Siendo todos los campos opcionales;
|Fabricantes|
:Completa los campos seleccionados;
|ZMGestion|
:Busca por producto, tela, lustre y estado de la orden de producción;
repeat while(No se encontraron coincidencias) is (V)
:Lista las coincidencias encontradas;
|Fabricantes|
end
@enduml

@startuml cancelarOrdenProduccion
|Administrador|
start
:Ha ejecutado con exito el CU084(Buscar avanzado órdenes de producción);
repeat
:Indica la orden de producción que desea cancelar;
repeat while(La orden de producción seleccionada no se encuentra en estado 'Pendiente' o 'En producción') is (V)
|ZMGestion|
:Ejecuta el CU(Cancelar línea de orden de producción) 
para cada linea de la orden de producción que se encuentre
en estado 'Pendiente de producción' o 'En producción'|
|Administrador|
end
@enduml

@startuml crearCliente
|Vendedor|
start
:Accede a la pantalla para crear clientes;
|ZMGestion|
repeat
repeat
repeat
:Muestra un formulario para que el vendedor ingrese el tipo de persona (física o jurídica),
nombre y apellido (o razón social), tipo y número de docuemento, correo electrónico, número de
telefono y nacionalidad;
|Vendedor|
:Completa el formulario;
|ZMGestion|
repeat while(El vendedor ha dejado un campo obligatorio vacío) is (V)
repeat while(El correo electrónico ingresado ya está en uso) is (V)
repeat while(El tipo y número de documento ingresado ya existe) is (V)
:Crea el cliente y muestra un mensaje indicando el éxito de la operación;
|Vendedor|
end
@enduml

@startuml crearPresupuesto
|Vendedor|
start
:Accede a la pantalla para crear presupuestos;
|ZMGestion|
repeat
:Muestra un formulario para que el vendedor seleccione un cliente y un campo autocompletado
con el perido de validez, que podrá modificar si cuenta con los permisos.;
|Vendedor|
:Selecciona un cliente y modifica el periodo de validez;
|ZMGestion|
repeat while(Ha seleccionado un cliente) is (F)
:Crea un presupuesto en estado de "En creación";
repeat
|Vendedor|
if(Desea agregar una línea de presupuesto) then (V)
:Ejecuta el CU064(Crear línea de presupuesto)|
else if (Desea modificar una línea de presupuesto) then (V)
:Ejecuta el CU065(Modificar línea de presupuesto)|
else if (Desea quitar una línea de presupuesto) then (V)
:Ejecuta el CU066(Modificar línea de presupuesto)|
endif
repeat while(Ha ingresado al menos una línea de presupuesto) is (F)
|ZMGestion|
:Cambia el estado del presupuesto a "Creado";
|Vendedor|
end
@enduml

@startuml crearProducto
|Administrador|
start
:Ingresa a la pantalla para crear productos;
|ZMGestion|
repeat
repeat
repeat
repeat
:Muestra un formulario para ingresar el nombre del 
producto, el precio, la cantidad de tela necesaria para
producirlo en caso de ser necesario, el tipo de producto y dos listas desplegables
para seleccionar la categoría y el grupo al cual pertenece
el producto. Indicando que todos los campos son requeridos, excepto por la cantidad de tela;
|Administrador|
:Completa el formulario y selecciona de las listas desplegables
el grupo y categoría a la cual pertenece el producto;
|ZMGestion|
repeat while (El administrador ha dejado un campo obligatorio vacío) is (V)
repeat while(El nombre ingresado ya existe para el grupo y categoría seleccionadas) is (V)
repeat while(El precio ingresado sea menor o igual que cero) is (V)
repeat while(La cantidad de tela necesaria ingresada sea menor que cero) is (V)
:Crea el producto con los campos ingresados por el usuario y 
 muestra un mensaje indicando el éxito de la operación;
|Administrador|
end
@enduml

@startuml crearProductoFinal
|Vendedor|
start
:Ingresa a la pantalla para crear productos finales;
|ZMGestion|
repeat
:Muestra un formulario para seleccionar el producto,
tipo de producto, tela y lustre;
|Vendedor|
:Selecciona el producto, tipo de producto, tela y lustre;
|ZMGestion|
repeat while(Un producto final ya existe con dicho producto, tipo de producto, tela y lustre.) is (V)
:Crea el producto final con los campos ingresados por el vendedor y 
 muestra un mensaje indicando el éxito de la operación;
|Vendedor|
end
@enduml

@startuml crearRol
|Administrador|
start
:Accede la la pantalla para crear roles;
|ZMGestion|
repeat
repeat
:Muestra un formulario para que el administador ingrese el nombre del rol
y seleccione los permisos que desea otorgarle. Indicando que ambos campos
son obligatorios;
|Administrador|
:Completa los campos requeridos;
|ZMGestion|
repeat while(Alguno de los campos obligatorios se encuentra vacío) is (V)
repeat while(El nombre ingresado ya está en uso) is (V)
:Crea el rol y muestra un mensaje indicando el éxito de la operación;
|Administrador|
end
@enduml

@startuml crearTela
|Administrador|
start 
:Accede a la pantalla para crear telas;
|ZMGestion|
repeat
repeat
repeat
:Muestra un formulario para que el usuario ingrese
el nombre y el precio por metro de tela. Indicando que
ambos campos son obligatorios;
|Administrador|
:Completa los campos requeridos;
|ZMGestion|
repeat while(Alguno de los campos obligatorios se encuentra vacío) is (V)
repeat while(El nombre ingresado ya se encuentra en uso) is (V)
repeat while(El precio ingresado sea menor o igual que cero) is (V)
:Crea la tela y muestra un mensaje 
indicando el éxito de la operación;
|Administrador|
end
@enduml

@startuml crearVenta
|Vendendor|
start
:Accede a la pantalla para crear ventas;
|ZMGestion|
repeat
:Muestra un formulario para que el vendendor seleccione un cliente;
|Vendendor|
:Selecciona un cliente;
|ZMGestion|
repeat while(No se ha seleccionado ningún cliente) is (V)
:Crea la venta en estado 'En creación' para el cliente seleccionado;
|Vendendor|
repeat
if(Desea agregar una línea de venta) then (V)
:Ejecuta el CU074(Crear línea de venta)|
else if (Desea quitar una línea de venta) then (V)
:Ejecuta el CU075(Modificar línea de venta)|
else if (Desea quitar una línea de venta) then (V)
:Ejecuta el CU076(Borrar línea de venta)|
endif
repeat while(No se ha agregado ninguna línea de venta) is (V)
|ZMGestion|
if(Todas las líneas de venta tienen el precio actual de los productos) then (V)
:Pasa el estado de la venta a 'Pendiente';
else (F)
:Pasa el estado de la venta a 'En revisión';
endif
|Vendendor|
end
@enduml

@startuml crearOrdenProduccion
|Administrador|
start
:Accede a la panatalla para crear órdenes de producción;
|ZMGestion|
:Crea una orden de producción en estado de `En creación';
|Administrador|
if(Desea agregar una línea de orden de producción) then (V)
:Ejecuta el CU103(Crear línea de orden de producción)|
else if (Desea quitar una línea de orden de producción) then (V)
:Ejecuta el CU104(Modificar línea de orden de producción)|
else if (Desea quitar una línea de orden de producción) then (V)
:Ejecuta el CU105(Borrar línea de orden de producción)|
endif
|ZMGestion|
if (Se agrego al menos una línea de orden de producción) then (V)
:Crea el estado de la orden de producción a `Pendiente';
endif
|Administrador|
end
@enduml 

@startuml crearLineaOrdenProduccion
|Administrador|
start 
:Desea agregar una linea de orden de producción;
|ZMGestion|
repeat
repeat
repeat
:Muestra un formulario para que el administrador seleccione el producto, tela y lustre
junto con la cantidad que desea producir del mismo;
|Administrador|
:Selecciona el producto, tela, lustre y cantidad a producir;
|ZMGestion|
repeat while (La cantidad ingresada es menor o igual que cero) is (V)
repeat while (El producto, tela y lustre indicado ya se encuentra en la orden de producción) is (V)
repeat while (El producto indicado no es del tipo producible) is (V)
if(Si la combinacion de producto, tela y lustre no existe) then (V)
:Ejecuta el CU025(Crear producto final) para el producto, tela y lustre seleccionado|
endif
:Crea la linea de orden de producción en estado de 'Pendiente de producción' 
y la asociacia a la orden de produción correspondiente;
|Administrador|
end

@enduml

@startuml darAltaTela
|Administrador|
start
:Ha ejecutado con éxito el CU Listar telas;
repeat
:Indica la tela que quiere dar de alta;
repeat while (La tela ya se encuentra en el estado de Alta) is (V)
|ZMGestion|
:Da de alta la tela y muesta un mensaje indicando el 
éxito de la operación;
|Administrador|
end
@enduml

@startuml darAltaProducto
|Administrador|
start
:Ha ejecutado con exito el CU Buscar avanzado productos;
repeat
:Indica el producto que quiere dar de alta;
repeat while(El producto ya se encuentra en estado de Alta) is (V)
|ZMGestion|
:Da de alta el producto indicado y muestra un mensaje 
indicando el éxito de la operación;
|Administrador|
end
@enduml

@startuml darBajaTela
|Administrador|
start 
:Ha ejecutado con exito el CU Listar telas;
repeat
:Indica la tela que desea dar de baja;
repeat while(La tela ya se encuentra en estado Baja) is (V)
|ZMGestion|
:Da de baja la tela y muestra un mensaje indicando que
la operación se realizo con éxito;
|Administrador|
end
@enduml

@startuml darBajaProducto
|Administrador|
start
:Ha ejecutado con éxito el CU BuscarAvanzadoProductos;
repeat
:Selecciona el producto que desea dar de baja;
repeat while(El producto ya se encuentra en estado de baja) is (V)
|ZMGestion|
:Da de baja el producto y muestra un mensaje indicando el éxito de la operación;
|Administrador|
end
@enduml

@startuml enviarPresupuestoEmail
|Vendedor|
:Ha ejecutado con éxito el CU057(Buscar avanzado presupuestos);
repeat
:Selecciona el presupuesto que desea enviar por correo electrónico;
|ZMGestion|
:Genera en formato PDF el presupuesto;
repeat while(Ël cliente no posee un correo electrónico) is (V)
:Envia el presupuesto por correo electrónico al correo del cliente asociado al presupuesto;
|Vendedor|
end
@enduml

@startuml generarPresupuestoPDF
|Vendedor|
start
:Ha ejecutado con éxito el CU057(Buscar avanzado presupuestos);
:Selecciona el presupuesto para generarlo en formato PDF;
|ZMGestion|
:Genera un achivo con formato PDF con los datos del presupuesto;
|Vendedor|
end
@enduml

@startuml generarOrdenProduccionDesdeVenta
|Administrador|
start
:Ha ejecutado con éxito el CU068(Buscar avanzado ventas);
:Selecciona la venta a partir de la cual desea generar la orden de producción;
|ZMGestion|
:Ejecuta el CU069 Listar líneas de venta para la venta seleccionada|
|Administrador|
repeat
:Selecciona las líneas de venta que desea agregar a la orden de producción;
repeat while (Selecciona una línea de venta cuyo producto no es del tipo producible) is (V)
|ZMGestion|
:Crea una orden de producción en estado 'En creación';
:Ejecuta el CU091(Crear línea de orden de producción) con los valores de producto, tela, lustre y cantidad de las
líneas de venta seleccionadas;
|Administrador|
repeat
if (Desea modificar una línea de orden de producción) then (V)
:Ejecuta el CU092(Modificar línea de orden de producción)|
else if (Desdea agregar una línea de orden de producción) then (V)
:Ejecuta el CU091(Crear línea de orden de producción)|
else if (Desea quitar alguna línea de orden de producción agregada) then (V)
:Ejecuta el CU093(Borrar línea de orden de producción)|
endif
repeat while (La orden de producción no tiene ninguna línea de orden de producción asignada)
|ZMGestion|
:Pasa el estado de la orden de producción a `Pendiente';
|Administrador|
end
@enduml

@startuml iniciarSesion
|Usuario|
start
:Ingresa la dirección de la aplicación en un dispositivo
conectado a Internet;
|ZMGestion|
repeat
repeat
repeat
:Muestra un formulario para que el usuario ingrese su
nombre de usuario y contraseña;
|Usuario|
:El usuario introduce su nombre de usuario y contraseña;
|ZMGestion|
repeat while(El nombre de usuario ingresado existe) is (F)
repeat while(El usuario se encuentra activo) is (F)
repeat while(La contraseña ingresada es incorrecta 
y no supero el límite de intentos permitidos) is (V)
if(La contraseña ingresada es incorrecta 
y supero el límite de intentos permitidos ) then (V)
:Bloquea al usuario;
else (F)
:Genera el token de sesión y lo almacena;
:Trae los permisos del usuario y le muestra sus opciones;
endif
|Usuario|
end
@enduml

@startuml listarLineasPresupuesto
|Vendedor|
start
:He ejecutado con éxito el CU057(Buscar avanzado presupuesto);
repeat
:Indica el presupuesto del cual desea listar las líneas de presupuesto;
repeat while(El presupuesto no posee líneas de presupuesto) is (V)
|ZMGestion|
:Lista las líneas de presupuesto;
|Vendedor|
end
@enduml

@startuml listarTelas
|Vendedor|
start
:Accede a la pantalla para listar las telas;
|ZMGestion|
if(Existe alguna tela en el sistema) then (V)
:Muestra una lista con las telas existentes;
else (F)
:Muestra un mensaje indicando que no existe ninguna tela;
endif
|Vendedor|
end
@enduml

@startuml listarLineasOrdenProduccion
|Fabricante|
start
:He ejecutado con éxito el CU084(Buscar avanzado ordenes de producción);
repeat
:Indica la orden de producción del cual desea listar las líneas de presupuesto;
repeat while(La orden de producción no posee líneas de orden de producción) is (V)
|ZMGestion|
:Lista las líneas de orden de producción;
|Fabricante|
end
@enduml

@startuml listarObservacionesLineaOrdenProduccion
|Fabricante|
start
:He ejecutado con éxito el CU084(Listar líneas de orden de producción);
repeat
:Indica la línea de orden de producción de la cual desea listar las observaciones;
repeat while(La línea de orden de producción no posee observaciones) is (V)
|ZMGestion|
:Lista las obseravaciones de la línea de orden de producción;
|Fabricante|
end
@enduml

@startuml modificarPresupuesto
|Vendedor|
start 
:Ha ejecutado con éxito el CU057(Buscar avanzado presupuestos);
repeat
repeat
:Selecciona el presupuesto que desea modificar;
repeat while(El presupuesto se encuentra en estado "Vendido") is (V)
repeat while (El vendedor que esta intentando modificar el presupuesto no es administrador 
y el presupuesto no le pertenece)
|ZMGestion|
repeat
repeat
:Muestra un formulario autocompletado con el cliente y periodo de validez del presupuesto,
si cuenta con los permisos podra modifica el periodo de validez;
|Vendedor|
:Modifica el cliente y periodo de validez;
|ZMGestion|
repeat while(El vendedor ha dejado alguno de los campos vacios) is (V)
repeat while(El vendedor ha modificado el periodo de validez y no tiene permisos) is (V)
:Ejecuta el CU058(Listar líneas de presupuesto) para el presupuesto seleccionado|
|Vendedor|
if(Desdea agregar una línea de presupuesto) then (V)
:Ejecuta el CU059(Crear línea de presupuesto)|
else if  (Desea modificar una línea de presupuesto) then (V)
:Ejecuta el CU060(Modificar línea de presupuesto)|
else if (Desea borrar una línea de presupuesto) then (V)
:Ejecuta el CU061(Borrar línea de presupuesto)|
endif
|ZMGestion|
:Modifica el presupuesto seleccionado y muestra un mensaje indicando el éxito de la operación;
|Vendedor|
end
@enduml

@startuml modificarProducto
|Administrador|
start
:Ha ejecutado el CU014(Buscar avanzado producto) con éxito;
:Selecciona el producto que desea modificar;
|ZMGestion|
repeat
repeat
repeat
repeat
:Muestra un formulario autocompletado con los datos del producto
seleccionado para que el administrador modifique nombre, tipo de producto, categoría, grupo,
cantidad de tela necesaria y precio. Indicando que todos los campos son obligatorios, exceptuando por la
cantidad de tela necesaria;
|Administrador|
:Modifica los campos que desea cambiar;
|ZMGestion|
repeat while(Alguno de los campos requeridos se encuentra vacío) is (V)
repeat while(El nombre, grupo y categoría ingresados ya estan en uso) is (V)
repeat while(El precio es menor o igual que cero) is (V)
repeat while(La cantidad de tela necesaria es menor que cero) is (V)
:Modifica el producto con los datos ingresados y muestra un mensaje idnicando el éxito de la operación;
|Administrador|
end
@enduml

@startuml modificarTela
|Administrador|
:Ha ejecutado con éxito el CU (Listar telas);
:Indica la tela que desea modificar;
|ZMGestion|
repeat
repeat
repeat
:Muestra un formulario autocompletado con los datos de la tela seleccionada
para que el administrador modifique: nombre y precio por metro de la tela.
Indicando que ambos campos son obligatorios;
|Administrador|
:Modifica los campos que desea cambiar;
|ZMGestion|
repeat while(El nombre de la tela se encuentra en uso) is (V)
repeat while(El precio ingresado es menor o igual a cero) is (V)
repeat while(Al menos un campo requerido está vacío) is (V)
:Modifica la tela y muestra un mensaje indicando
el éxito de la operación;
|Administrador|
end
@enduml

@startuml modificarVenta
|Vendedor|
start 
:Ha ejecutado con éxito el CU063(Buscar avanzado ventas);
repeat
repeat
:Selecciona la venta que desea modificar;
repeat while(La venta no se encuentra en estado 'En creación') is (V)
repeat while (El vendedor que esta intentando modificar la venta no es administrador 
y la venta no le pertenece) is (V)
|ZMGestion|
repeat
:Muestra un formulario autocompletado con el cliente.;
|Vendedor|
:Modifica el cliente;
|ZMGestion|
repeat while(El vendedor ha dejado el cliente vacío) is (V)
:Ejecuta el CU064(Listar líneas de venta) para la venta seleccionada|
|Vendedor|
if(Desdea agregar una línea de venta) then (V)
:Ejecuta el CU067(Crear línea de venta)|
else if  (Desea modificar una línea de venta) then (V)
:Ejecuta el CU068(Modificar línea de venta)|
else if (Desea borrar una línea de venta) then (V)
:Ejecuta el CU069(Borrar línea de venta)|
endif
|ZMGestion|
:Modifica la venta seleccionada y muestra un mensaje indicando el éxito de la operación;
|Vendedor|
end
@enduml

@startuml revisarVenta
|Administrador|
start
:Ha ejecutado con éxito el CU068(Buscar avanzado ventas);
repeat
:Selecciona la venta la cual desea revisar;
repeat while(La venta seleccionada se encuentra en estado 'En revisión') is (V)
|ZMGestion|
:Muestra el cliente al cual pertenece la venta y ejecuta el CU069(Listar líneas de venta)
para la venta seleccionada;
:Indica las líneas de venta que poseen el precio desactualizado;
|Administrador|
if(Desea aceptar la venta) then (V)
|ZMGestion|
:Pasa la venta al estado de 'Pendiente;
|Administrador|
else (F)
|ZMGestion|
:Pasa la venta al estado de 'Cancelada';
endif
:Muestra un mensaje indicando el éxito de la operación;
|Administrador|
end

@enduml


@startuml transformarPresupuestosEnVenta
|Vendedor|
start
:Ha ejecutado con éxito el CU057(Buscar avanzado presupuestos);
repeat
:Selecciona el/los presupuesto/s a partir de los cuales desea generar la venta;
repeat while(Al menos un presupuesto seleccionado se encuentra en estado de "Vendido") is (V)
|ZMGestion|
repeat
:Muestra un formulario para que el vendedor seleccione
el cliente y ejecuta el CU058(Listar líneas de presupuesto)
para cada presupuesto seleccionado, mostrando una opción por
cada línea si desea añadirla a la venta ;
|Vendedor|
:Selecciona el cliente y elige las líneas de presupuesto que desea agregar;
|ZMGestion|
repeat while(El vendedor ha dejado el cliente vacío) is (V)
:Crea un venta para el cliente seleccionado en estado de "En creación"
y ejecuta el CU067(Crear línea de venta) con los valores de producto, cantidad 
y precio de cada línea de presupuesto seleccionada;
|Vendedor|
repeat
if (Desea modificar una línea de venta) then (V)
:Ejecuta el CU075(Modificar línea de venta)|
else if (Desdea agregar una línea de venta) then (V)
:Ejecuta el CU074(Crear línea de venta)|
else if (Desea quitar alguna línea de venta agregada) then (V)
:Ejecuta el CU076(Borrar línea de venta)|
endif
repeat while(La venta no tiene ninguna línea de venta asociada) is (V)
|ZMGestion|
if(Todas las líneas de venta tienen el precio actual de los productos) then (V)
:Pasa el estado de la venta a 'Pendiente';
:Pasa el estado de la líneas de presupuesto utilizadas a `Utilizada' y de las no utilizadas a `No utilizada';
else (F)
:Pasa el estado de la venta a 'En revisión';
endif
|Vendedor|
end
@enduml