@startuml DiagramaContexto
!include ../Actors/Actors.wsd

left to right direction

/'Definicion del paquete'/
package ZMGestion{

}

/'Relacion de los actores con el paquete'/
Usuarios ..|> ZMGestion
Administradores ..|> ZMGestion
Vendedores ..|> ZMGestion
Fabricantes ..|> ZMGestion
@enduml

@startuml DiagramaSubsistema
!include ../Actors/Actors.wsd

left to right direction

rectangle ZMGestion{
    rectangle Sesiones{
    }
    rectangle GestionEmpleados{
        
    }
    rectangle GestionArticulosVenta{
        
    }
    rectangle GestionOperaciones{
        
    }
    rectangle GestionStock{
        
    }
    
    rectangle GestionClientes{
    }

    Usuarios  ..|> Sesiones
    Administradores ..|> GestionEmpleados
    Usuarios ..|> GestionOperaciones
    Vendedores  ..|> GestionStock
    Vendedores  ..|> GestionArticulosVenta
    Vendedores ..|> GestionClientes
}

@enduml

@startuml DiagramaSubsistemaDetallado
!include ../Actors/Actors.wsd

left to right direction

rectangle ZMGestion{
    rectangle Sesiones{
    }
    rectangle GestionEmpleados{
        rectangle GestionRoles{
        }
    }
    rectangle GestionArticulosVenta{
        rectangle GestionProductos{
        }
        rectangle GestionTelas{
        }
        rectangle GestionProductosFinales{
        }
        rectangle GestionGruposProducto{
        }
    }
    rectangle GestionOperaciones{
        rectangle GestionPresupuestos{
            rectangle GestionLineasPresupuesto{
            }
        }
        rectangle GestionVentas{
            rectangle GestionLineasVenta{
            }
            rectangle GestionComprobantes{
            }
        }
        rectangle GestionOrdenesProduccion{
            rectangle GestionLineasOrdenesProduccion{
            }
            rectangle GestionObservaciones{
            }
        }
    }
    rectangle GestionStock{
        rectangle GestionRemitos{
        }
        rectangle GestionUbicaciones{
        }
    }
    
    rectangle GestionClientes{
        rectangle GestionDomicilios{
        }
    }

    Usuarios  ..|> Sesiones
    Administradores ..|> GestionEmpleados
    Usuarios ..|> GestionOperaciones
    Vendedores  ..|> GestionStock
    Vendedores  ..|> GestionArticulosVenta
    Vendedores ..|> GestionClientes
}

@enduml

@startuml Sesiones
!include ../Actors/Actors.wsd
 left to right direction

rectangle Sesiones{
    UseCase "CU001 - Iniciar sesión" as Iniciar
    UseCase "CU002 - Cerrar sesión " as Cerrar
}
    Usuarios -- Iniciar
    Usuarios -- Cerrar

@enduml

@startuml GestionEmpleados
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionEmpleados{
    UseCase "CU003 - Crear empleado" as C
    UseCase "CU004 - Buscar avanzado empleados" as BA
    UseCase "CU005 - Dar de baja empleado" as DB
    UseCase "CU006 - Dar de alta empleado" as DA
    UseCase "CU007 - Modificar empleado" as M
    UseCase "CU008 - Borrar empleado" as B
    rectangle GestionRoles as Roles{
    }
    BA <|.. M : <<Extends>>
    BA <|.. DA : <<Extends>>
    BA <|.. DB : <<Extends>>
    BA <|.. B : <<Extends>>
}
    Administradores -- C
    Administradores -- BA
    Administradores -- Roles

    

@enduml

@startuml GestionRoles
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionRoles{
    UseCase "CU009 - Crear rol" as C
    UseCase "CU010 - Listar roles " as L
    UseCase "CU011 - Modificar rol" as M
    UseCase "CU012 - Borrar rol" as B
    L <|.. M : <<Extends>>
    L <|.. B : <<Extends>>
}
    Administradores -- C
    Administradores -- L

@enduml

@startuml GestionArticulosVenta
!include ../Actors/Actors.wsd
 left to right direction
rectangle GestionArticulosVenta{
    rectangle GestionProductos as Productos{
    }
    rectangle GestionTelas as Telas{ 
    }
    rectangle GestionProductosFinales as ProductosFinales{
    }
    rectangle GestionGruposProductos as GruposProductos{
    }
}
    Vendedores -- Productos
    Vendedores -- Telas
    Vendedores -- ProductosFinales
    Administradores -- GruposProductos 

@enduml

@startuml GestionProductos
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionProductos{
    UseCase "CU013 - Crear producto" as C
    UseCase "CU014 - Buscar avanzado productos " as BA
    UseCase "CU015 - Dar de baja producto" as DB
    UseCase "CU016 - Dar de alta producto" as DA
    UseCase "CU017 - Modificar producto" as M
    UseCase "CU018 - Borrar producto" as B
    BA <|.. M : <<Extends>>
    BA <|.. DA : <<Extends>>
    BA <|.. DB : <<Extends>>
    BA <|.. B : <<Extends>>
}
    Administradores -- C
    Vendedores -- BA
    Administradores -- M
    Administradores -- B
    Administradores -- DB
    Administradores -- DA

@enduml

@startuml GestionTelas
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionTelas{
    UseCase "CU019 - Crear tela" as C
    UseCase "CU020 - Listar telas " as L
    UseCase "CU021 - Dar de baja tela" as DB
    UseCase "CU022 - Dar de alta tela" as DA
    UseCase "CU023 - Modificar tela" as M
    UseCase "CU024 - Borrar tela" as B
    L <|.. M : <<Extends>>
    L <|.. DA : <<Extends>>
    L <|.. DB : <<Extends>>
    L <|.. B : <<Extends>>
}
    Administradores -- C
    Vendedores -- L
    Administradores -- M
    Administradores -- B
    Administradores -- DB
    Administradores -- DA

@enduml

@startuml GestionProductosFinales
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionProductosFinales{
    UseCase "CU025 - Crear producto final" as C
    UseCase "CU026 - Buscar avanzado productos finales" as BA
    UseCase "CU027 - Dar de baja producto final" as DB
    UseCase "CU028 - Dar de alta producto final" as DA
    UseCase "CU029 - Modificar producto final" as M
    UseCase "CU030 - Borrar producto final" as B
    BA <|.. M : <<Extends>>
    BA <|.. DA : <<Extends>>
    BA <|.. DB : <<Extends>>
    BA <|.. B : <<Extends>>
}
    Vendedores -- BA
    Vendedores -- C
    Administradores -- B
    Administradores -- DB
    Administradores -- DA
    Administradores -- M

@enduml

@startuml GestionGruposProducto
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionGruposProducto{
    UseCase "CU031 - Crear grupo de producto" as C
    UseCase "CU032 - Listar grupos de producto" as L
    UseCase "CU033 - Dar de baja grupo de producto" as DB
    UseCase "CU034 - Dar de alta grupo de producto" as DA
    UseCase "CU035 - Modificar grupo de producto" as M
    UseCase "CU036 - Borrar grupo de producto" as B
    UseCase "CU037 - Listar productos por grupo" as Listar
    UseCase "CU038 - Modificar precios grupo" as Precios

    L <|.. M : <<Extends>>
    L <|.. DA : <<Extends>>
    L <|.. DB : <<Extends>>
    L <|.. B : <<Extends>>
    L <|.. Listar : <<Extends>>
    L <|.. Precios : <<Extends>>
}
    Administradores -- C
    Administradores -- L

@enduml

@startuml GestionStock
!include ../Actors/Actors.wsd
 left to right direction
rectangle GestionStock{
    rectangle GestionRemitos as Remitos{
    }
    rectangle GestionUbicaciones as Ubicaciones{
    }
}
    Vendedores -- Remitos
    Vendedores -- Ubicaciones
@enduml

@startuml GestionUbicaciones
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionUbicaciones{
    UseCase "CU039 - Crear ubicación" as C
    UseCase "CU040 - Listar ubicaciones " as L
    UseCase "CU041 - Dar de baja ubicación" as DB
    UseCase "CU042 - Dar de alta ubicación" as DA
    UseCase "CU043 - Modificar ubicación" as M
    UseCase "CU044 - Borrar ubicación" as B

    L <|.. M : <<Extends>>
    L <|.. DA : <<Extends>>
    L <|.. DB : <<Extends>>
    L <|.. B : <<Extends>>
}
    Administradores -- C
    Vendedores -- L
    Administradores -- M
    Administradores -- B
    Administradores -- DB
    Administradores -- DA

@enduml

@startuml GestionRemitos
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionRemitos{
    UseCase "CU045 - Crear remito" as C
    UseCase "CU046 - Buscar avanzado remitos " as BA
    UseCase "CU047 - Cancelar remito" as Cancelar
    UseCase "CU048 - Descancelar remito" as Descancelar
    UseCase "CU049 - Entregar remito" as Entregar
    UseCase "CU050 - Borrar remito" as B
    UseCase "CU051 - Listar lineas remito" as Listar
    package GestionLineasRemito{
    }
    
    BA <|.. B : <<Extends>>
    BA <|.. Listar : <<Extends>>
    BA <|.. Entregar : <<Extends>>
    BA <|.. Cancelar : <<Extends>>
    BA <|.. Descancelar : <<Extends>>
    Listar <|.. GestionLineasRemito : <<Extends>>
    C <|.. GestionLineasRemito : <<Extends>>
}
    Vendedores -- C
    Vendedores -- BA
    Administradores -- B
    Administradores -- Cancelar
    Administradores -- Descancelar

@enduml

@startuml GestionLineasRemito
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionLineasRemito{
    UseCase "CU052 - Crear linea de remito" as C
    UseCase "CU053 - Modificar linea de remito" as M
    UseCase "CU054 - Borrar linea de remito" as B
}
    Vendedores -- C
    Administradores -- B
    Vendedores -- M

@enduml

@startuml GestionClientes
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionClientes{
    UseCase "CU055 - Crear cliente" as C
    UseCase "CU056 - Buscar avanzado clientes" as BA
    UseCase "CU057 - Dar de baja cliente" as DB
    UseCase "CU058 - Dar de alta cliente" as DA
    UseCase "CU059 - Modificar cliente" as M
    UseCase "CU060 - Borrar cliente" as B
    UseCase "CU061 - Listar domicilios" as ListarDomicilios
    package GestionDomicilios{
    }
    BA <|.. M : <<Extends>>
    BA <|.. DA : <<Extends>>
    BA <|.. DB : <<Extends>>
    BA <|.. B : <<Extends>>
    C <|.. B : <<Extends>>
    BA <|.. ListarDomicilios : <<Extends>>
    BA <|.. GestionDomicilios : <<Extends>>
}
    Vendedores -- C
    Vendedores -- BA
    Administradores -- DB
    Administradores -- DA

@enduml

@startuml GestionDomicilios
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionDomicilios{
    UseCase "CU062 - Crear domicilio" as C
    UseCase "CU063 - Borrar domicilio" as B
}
    Vendedores -- C
    Vendedores -- B

@enduml

@startuml GestionOperaciones
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionOperaciones{
    rectangle GestionPresupuestos as Presupuestos{
            rectangle GestionLineasPresupuesto{
            }
        }
        rectangle GestionVentas as Ventas{
            rectangle GestionLineasVenta{
            }
            rectangle GestionComprobantes{
            }
        }
        rectangle GestionOrdenesProduccion as OrdenesProduccion{
            rectangle GestionLineasOrdenesProduccion{
            }
            rectangle GestionObservaciones{
            }
        }
}
    Vendedores -- Presupuestos
    Vendedores -- Ventas
    Fabricantes -- OrdenesProduccion

@enduml

@startuml GestionPresupuestos
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionPrespuestos{
    UseCase "CU064 - Crear presupuesto" as C
    UseCase "CU065 - Buscar avanzado presupuestos" as BA
    UseCase "CU066 - Modificar presupuesto" as M
    UseCase "CU067 - Borrar presupuesto" as B
    UseCase "CU068 - Transformar presupuestos en venta" as Transformar
    UseCase "CU069 - Generar presupuesto en formato PDF" as PDF
    UseCase "CU070 - Enviar presupuesto por correo electrónico" as Enviar
    UseCase "CU071 - Listar lineas de presupuesto" as Listar
    package GestionLineasPresupuesto{
    }

    BA <|.. M : <<Extends>>
    BA <|.. B : <<Extends>>
    Listar <|.. Transformar : <<Extends>>
    Listar <|.. GestionLineasPresupuesto : <<Extends>>
    C <|.. GestionLineasPresupuesto : <<Extends>>
    BA <|.. PDF : <<Extends>>
    BA <|.. Enviar : <<Extends>>
    BA <|.. Listar: <<Extends>>
}
    Vendedores -- C
    Vendedores -- BA
    Administradores -- B

@enduml

@startuml GestionLineasPresupuesto
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionLineasPresupuesto{
    UseCase "CU072 - Crear linea de prespuesto" as C
    UseCase "CU073 - Modificar linea de presupuesto" as M
    UseCase "CU074 - Borrar linea de presupuesto " as B
}
    Vendedores -- C
    Vendedores -- M
    Administradores --  B

@enduml

@startuml GestionVentas
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionVentas{
    UseCase "CU075 - Crear venta" as C
    UseCase "CU076 - Buscar avanzado ventas " as BA
    UseCase "CU077 - Listar lineas de venta " as Listar
    UseCase "CU078 - Modificar venta" as M
    UseCase "CU079 - Borrar venta" as B
    UseCase "CU080 - Generar orden de producción a partir de venta" as GenerarOrden
    UseCase "CU081 - Generar remito a partir de venta" as GenerarRemito
    UseCase "CU082 - Crear comprobante" as CrearComprobante
    UseCase "CU083 - Revisar venta" as Revisar
    package GestionLineasVenta{
    }
    package GestionComprobantes{
    }

    BA <|.. M : <<Extends>>
    BA <|.. B : <<Extends>>
    BA <|.. Listar : <<Extends>>
    BA <|.. CrearComprobante : <<Extends>>
    Listar <|.. GestionLineasVenta : <<Extends>>
    BA <|.. GenerarOrden : <<Extends>>
    BA <|.. GenerarRemito : <<Extends>>
    C  <|.. GestionLineasVenta : <<Extends>>
}
    Vendedores -- C
    Vendedores -- GestionComprobantes
    Vendedores -- BA
    Administradores -- B
    Administradores -- Revisar

@enduml

@startuml GestionLineasVenta
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionLineasVenta{
    UseCase "CU084 - Crear linea de venta" as C
    UseCase "CU085 - Modificar linea de venta" as M
    UseCase "CU086 - Borrar linea de venta" as B
    UseCase "CU087 - Cancelar linea de venta" as Cancelar
}
    Vendedores -- C
    Vendedores -- B
    Vendedores -- M
    Administradores -- Cancelar


@enduml

@startuml GestionComprobantes
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionComprobantes{
    
    UseCase "CU088 - Buscar avanzado comprobantes " as BA
    UseCase "CU089 - Modificar comprobante" as M
    UseCase "CU090 - Borrar comprobante" as B

    BA <|.. M : <<Extends>>
    BA <|.. B : <<Extends>>
}
    Vendedores -- BA
    Administradores -- B
    Administradores -- M

@enduml


@startuml GestionOrdenesProduccion
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionOrdenesProduccion{
    UseCase "CU091 - Crear orden de producción" as C
    UseCase "CU092 - Buscar avanzado órdenes de producción " as BA
    UseCase "CU093 - Modificar orden de producción" as M
    UseCase "CU094 - Listar lineas de orden de producción" as ListarLineas
    UseCase "CU095 - Borrar orden de producción" as B
    UseCase "CU096 - Cancelar orden de producción" as Cancelar
    UseCase "CU097 - Listar observaciones de línea de orden de producción" as ListarObservaciones
    UseCase "CU098 - Listar tareas de línea de orden de producción" as ListarTareas
    package GestionLineasOrdenProduccion{
    }
    package GestionObservaciones{
    }
    package GestionTareas{
    }

    BA <|.. M : <<Extends>>
    BA <|.. B : <<Extends>>
    BA <|.. ListarLineas : <<Extends>>
    BA <|.. Cancelar : <<Extends>>
    ListarLineas <|.. ListarObservaciones : <<Extends>>
    ListarLineas <|.. ListarTareas : <<Extends>>
    C <|.. GestionLineasOrdenProduccion : <<Extends>>
    M <|.. GestionLineasOrdenProduccion : <<Extends>>
    ListarLineas <|.. GestionLineasOrdenProduccion : <<Extends>>
    ListarLineas <|.. GestionObservaciones : <<Extends>>
    ListarLineas <|.. GestionTareas : <<Extends>>
}
    Administradores -- C
    Fabricantes -- BA
    Administradores -- M
    Administradores -- B

@enduml

@startuml GestionLineasOrdenesProduccion
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionLineasOrdenesProduccion{
    UseCase "CU099 - Crear linea de orden de producción" as C
    UseCase "CU100 - Modificar linea de orden de producción" as M
    UseCase "CU101 - Borrar linea de orden de producción" as B
    UseCase "CU102 - Verificar linea de orden de producción" as Verificar
    UseCase "CU103 - Cancelar linea de orden de producción" as Cancelar
    UseCase "CU104 - Reanudar linea de orden de producción" as Reanudar
}
    Administradores -- C
    Administradores -- Verificar
    Administradores -- Cancelar
    Administradores -- Reanudar
    Administradores -- B
    Administradores -- M
    
@enduml

@startuml GestionObservaciones
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionObservaciones{
    UseCase "CU105 - Crear observación" as C
    UseCase "CU106 - Borrar observación" as B
}
    Administradores -- C
    Administradores -- B
@enduml

@startuml GestionTareas
!include ../Actors/Actors.wsd
 left to right direction

rectangle GestionTareas{
    UseCase "CU107 - Crear tarea" as C
    UseCase "CU108 - Borrar tarea" as B
    UseCase "CU109 - Finalizar tarea" as Finalizar
    UseCase "CU110 - Verificar tarea" as Verificar
    UseCase "CU111 - Pausar tarea" as Pausar
    UseCase "CU112 - Reanudar tarea" as Reanudar
    UseCase "CU113 - Cancelar tarea" as Cancelar
    UseCase "CU114 - Ejecutar tarea" as Ejecutar
}
    Administradores -- C
    Administradores -- B
    Administradores -- Verificar
    Administradores -- Pausar
    Administradores -- Reanudar
    Fabricantes -- Finalizar
    Fabricantes -- Ejecutar
    Administradores -- Cancelar
    

@enduml






